name: didkyo
description: A social travelbook.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.2
  flutter_bloc: ^3.2.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  another_flushbar: ^1.12.29
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  injectable_generator: ^2.1.3



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

